// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnlpWwF9tooWvnInS4ns_uC1nEUDK_ZTQ',
    appId: '1:1029369871339:web:1749bd2f78b2cd0ac477ae',
    messagingSenderId: '1029369871339',
    projectId: 'bitrisesample',
    authDomain: 'bitrisesample.firebaseapp.com',
    storageBucket: 'bitrisesample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPsbjpOmX2eSaWXGOSSOCF_gtmgClsyC4',
    appId: '1:1029369871339:android:805c461465dc76d7c477ae',
    messagingSenderId: '1029369871339',
    projectId: 'bitrisesample',
    storageBucket: 'bitrisesample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbzmncX6w2W3PLmcZRdxJ5sbH-_QyCQbY',
    appId: '1:1029369871339:ios:c35a41cc0c92a526c477ae',
    messagingSenderId: '1029369871339',
    projectId: 'bitrisesample',
    storageBucket: 'bitrisesample.appspot.com',
    iosClientId: '1029369871339-5bhh016anbel4gl001k9lhkcu700d4le.apps.googleusercontent.com',
    iosBundleId: 'com.byusneus.cli',
  );
}
